feat(generate-from-template): write build log file for debugging
americanexpress/create-using-template pull request #38
Opened 2022-11-21 22:47 UTC by 10xLaCroixDrinker

This writes a JSON file at each step with information about the template and the state of the process.

Example output:

```json
{
  "engines": {
    "node": "v16.18.1",
    "npm": "v7.24.2",
    "create-using-template": "v1.8.0"
  },
  "steps": {
    "1": {
      "status": "complete",
      "timestamp": 1669065919098
    },
    "2": {
      "status": "complete",
      "timestamp": 1669065928121
    },
    "3": {
      "status": "complete",
      "timestamp": 1669065928215
    },
    "4": {
      "status": "complete",
      "timestamp": 1669065928243
    },
    "5": {
      "status": "complete",
      "timestamp": 1669066004080
    },
    "6": {
      "status": "complete",
      "timestamp": 1669066008516
    }
  },
  "template": {
    "name": "my-template",
    "version": "v0.0.0",
    "values": {
      "projectName": "test-project",
      "description": "yada yada, blah blah",
      "codeowners": [
        "@ameericanexpress/one-app-team"
      ],
      "authorName": "Jamie King",
      "authorEmail": "jamie.king@aexp.com"
    }
  }
}
```

2022-11-28 20:09 UTC, giulianok requested changes

2022-11-28 20:11 UTC, 10xLaCroixDrinker commented on src/utils/create-build-logger.js
> +  const writeBuildLog = async () => fs.writeFile(buildLogPath, JSON.stringify(buildLog, null, 2));
It is important to write at each step in case there is a failure mid-process

2022-11-28 22:24 UTC, 10xLaCroixDrinker commented on src/utils/create-build-logger.js
> +  const writeBuildLog = async () => fs.writeFile(buildLogPath, JSON.stringify(buildLog, null, 2));
Refactored in [0fce7d2](https://github.com/americanexpress/create-using-template/pull/38/commits/0fce7d2b23103fd18009571a10f7c063d136d20b) to use process `exit` event

2022-11-29 11:30 UTC, code-forger commented on bin/index.js
> +  await buildLogger.addError(err);
addError is not async in utils/create-build-logger.js, does it need to be awaited here?

2022-11-29 11:31 UTC, code-forger commented on src/generate-from-template.js
> +  await buildLogger.addStep(1, 'complete');
Same thing throughout, do these need to be awaited, since none of the functions are async?

2022-11-29 11:31 UTC, code-forger approved these changes

2022-11-29 14:28 UTC, giulianok submitted a review, later dismissed

2022-11-29 16:32 UTC, giulianok approved these changes

2022-11-29 17:03 UTC, merged